import type {
  AuditLogEntry,
  Disease,
  Drug,
  EvidenceRecord,
  ReviewQueueItem,
  Target,
} from "./types";

export const drugs: Drug[] = [
  {
    slug: "metformin",
    name: "Metformin",
    genericName: "metformin",
    brandNames: ["Glucophage", "Fortamet"],
    mechanism:
      "Biguanide that decreases hepatic glucose production and improves insulin sensitivity via AMPK activation.",
    primaryIndication: "Type 2 diabetes mellitus",
    approvalStatus: "FDA approved (1995)",
    atcCode: "A10BA02",
    whyThisDrug:
      "Beyond glycemic control, metformin modulates AMPK/mTOR signaling and has demonstrated anti-proliferative effects in preclinical cancer models, with observational cohorts suggesting reduced cancer incidence in diabetic patients.",
    knownRisks: [
      "Lactic acidosis (rare, especially with renal impairment)",
      "GI upset",
      "Vitamin B12 deficiency with long-term use",
      "Contraindicated in severe renal dysfunction",
    ],
    targetSlugs: ["ampk", "mTOR"],
    relatedDiseaseSlugs: ["type-2-diabetes", "breast-cancer", "polycystic-ovary-syndrome"],
    similarDrugSlugs: ["rapamycin"],
  },
  {
    slug: "sildenafil",
    name: "Sildenafil",
    genericName: "sildenafil",
    brandNames: ["Viagra", "Revatio"],
    mechanism:
      "Selective phosphodiesterase-5 (PDE5) inhibitor that increases cGMP, promoting vasodilation.",
    primaryIndication: "Erectile dysfunction; pulmonary arterial hypertension",
    approvalStatus: "FDA approved (1998 ED; 2005 PAH)",
    atcCode: "G04BE03",
    whyThisDrug:
      "Originally developed for angina, sildenafil's vasodilatory profile was repurposed for erectile dysfunction and later PAH after clinicians observed hemodynamic effects in pulmonary circulation.",
    knownRisks: [
      "Hypotension (especially with nitrates)",
      "Headache and flushing",
      "Visual disturbances",
      "Priapism (rare)",
    ],
    targetSlugs: ["pde5"],
    relatedDiseaseSlugs: ["pulmonary-arterial-hypertension", "erectile-dysfunction"],
    similarDrugSlugs: [],
  },
  {
    slug: "thalidomide",
    name: "Thalidomide",
    genericName: "thalidomide",
    brandNames: ["Thalomid"],
    mechanism:
      "Immunomodulatory agent with anti-angiogenic properties; modulates TNF-α and cereblon-mediated protein degradation.",
    primaryIndication: "Multiple myeloma; erythema nodosum leprosum",
    approvalStatus: "FDA approved for myeloma (2006); REMS program required",
    atcCode: "L04AX02",
    whyThisDrug:
      "After catastrophic teratogenicity halted its use as a sedative, thalidomide was repurposed for leprosy complications and later multiple myeloma based on anti-angiogenic and immunomodulatory mechanisms.",
    knownRisks: [
      "Severe birth defects (absolute contraindication in pregnancy)",
      "Peripheral neuropathy",
      "Thromboembolism",
      "Sedation and constipation",
    ],
    targetSlugs: ["tnf-alpha", "cereblon"],
    relatedDiseaseSlugs: ["multiple-myeloma"],
    similarDrugSlugs: [],
  },
  {
    slug: "dexamethasone",
    name: "Dexamethasone",
    genericName: "dexamethasone",
    brandNames: ["Decadron", "DexPak"],
    mechanism:
      "Potent glucocorticoid that suppresses inflammatory and immune responses via glucocorticoid receptor activation.",
    primaryIndication: "Inflammatory and autoimmune conditions; oncology supportive care",
    approvalStatus: "FDA approved (1958)",
    atcCode: "H02AB02",
    whyThisDrug:
      "The RECOVERY trial demonstrated mortality benefit in hospitalized COVID-19 patients requiring oxygen, establishing dexamethasone as standard-of-care anti-inflammatory therapy in severe disease.",
    knownRisks: [
      "Hyperglycemia",
      "Immunosuppression and infection risk",
      "Adrenal suppression with prolonged use",
      "Mood changes and insomnia",
    ],
    targetSlugs: ["glucocorticoid-receptor"],
    relatedDiseaseSlugs: ["covid-19", "rheumatoid-arthritis"],
    similarDrugSlugs: [],
  },
  {
    slug: "rapamycin",
    name: "Sirolimus (Rapamycin)",
    genericName: "sirolimus",
    brandNames: ["Rapamune"],
    mechanism:
      "mTOR inhibitor that suppresses T-cell proliferation and angiogenesis.",
    primaryIndication: "Immunosuppression post-transplant; TSC-associated manifestations",
    approvalStatus: "FDA approved (1999 transplant; TSC indications expanded)",
    atcCode: "L04AA10",
    whyThisDrug:
      "Rapamycin inhibits mTOR signaling implicated in tuberous sclerosis complex (TSC) hamartoma growth, leading to approved use for TSC-associated SEGA and renal angiomyolipoma.",
    knownRisks: [
      "Immunosuppression",
      "Hyperlipidemia",
      "Mouth ulcers",
      "Impaired wound healing",
    ],
    targetSlugs: ["mTOR"],
    relatedDiseaseSlugs: ["tuberous-sclerosis"],
    similarDrugSlugs: ["metformin"],
  },
  {
    slug: "levothyroxine",
    name: "Levothyroxine (Synthroid)",
    genericName: "levothyroxine",
    brandNames: ["Synthroid", "Levoxyl", "Tirosint"],
    mechanism:
      "Synthetic T4 thyroid hormone replacement that restores euthyroid state via thyroid hormone receptor activation.",
    primaryIndication: "Hypothyroidism",
    approvalStatus: "FDA approved",
    atcCode: "H03AA01",
    whyThisDrug:
      "Levothyroxine is the gold-standard hormone replacement for hypothyroidism, with decades of clinical evidence, FDA-approved labeling, and guideline endorsement from endocrine societies.",
    knownRisks: [
      "Overtreatment causing thyrotoxicosis",
      "Cardiac arrhythmias if overdosed",
      "Bone loss with supraphysiologic doses",
      "Drug–food interactions (calcium, iron)",
    ],
    targetSlugs: ["thyroid-hormone-receptor"],
    relatedDiseaseSlugs: ["hypothyroidism"],
    similarDrugSlugs: [],
  },
  {
    slug: "aspirin",
    name: "Aspirin",
    genericName: "acetylsalicylic acid",
    brandNames: ["Bayer Aspirin", "Ecotrin"],
    mechanism:
      "Irreversible COX-1/COX-2 inhibitor; antiplatelet at low doses via thromboxane A2 suppression.",
    primaryIndication: "Cardiovascular disease prevention; analgesia",
    approvalStatus: "FDA approved",
    atcCode: "B01AC06",
    whyThisDrug:
      "Low-dose aspirin is a cornerstone of secondary cardiovascular prevention with extensive RCT evidence (Antithrombotic Trialists' Collaboration) supporting antiplatelet therapy in high-risk patients.",
    knownRisks: [
      "GI bleeding and ulceration",
      "Hemorrhagic stroke (low absolute risk)",
      "Reye syndrome in children",
      "Allergy (aspirin-exacerbated respiratory disease)",
    ],
    targetSlugs: ["cox1", "cox2"],
    relatedDiseaseSlugs: ["cardiovascular-disease"],
    similarDrugSlugs: [],
  },
  {
    slug: "finasteride",
    name: "Finasteride",
    genericName: "finasteride",
    brandNames: ["Proscar", "Propecia"],
    mechanism:
      "5α-reductase inhibitor that reduces dihydrotestosterone (DHT) synthesis.",
    primaryIndication: "Benign prostatic hyperplasia; androgenetic alopecia",
    approvalStatus: "FDA approved (BPH 1992; alopecia 1997)",
    atcCode: "G04CB01",
    whyThisDrug:
      "Finasteride was developed for BPH and serendipitously found to promote hair regrowth, leading to a second approved indication for androgenetic alopecia—a classic mechanistic repurposing story.",
    knownRisks: [
      "Sexual dysfunction",
      "Depression (reported, debated incidence)",
      "PSA reduction (masking prostate cancer screening)",
      "Contraindicated in pregnancy (teratogenic)",
    ],
    targetSlugs: ["5-alpha-reductase"],
    relatedDiseaseSlugs: ["benign-prostatic-hyperplasia", "androgenetic-alopecia"],
    similarDrugSlugs: [],
  },
  {
    slug: "minoxidil",
    name: "Minoxidil",
    genericName: "minoxidil",
    brandNames: ["Rogaine", "Loniten"],
    mechanism:
      "ATP-sensitive potassium channel opener causing vasodilation; hair growth mechanism partially via VEGF upregulation.",
    primaryIndication: "Hypertension (oral); androgenetic alopecia (topical)",
    approvalStatus: "FDA approved",
    atcCode: "C02DC01",
    whyThisDrug:
      "Oral minoxidil was approved for refractory hypertension; hypertrichosis side effect led to topical formulation development for androgenetic alopecia—one of the most cited serendipitous repurposing cases.",
    knownRisks: [
      "Fluid retention and tachycardia (oral)",
      "Scalp irritation (topical)",
      "Hypertrichosis at unintended sites",
      "Pericardial effusion (oral, rare)",
    ],
    targetSlugs: ["k-atp-channel"],
    relatedDiseaseSlugs: ["androgenetic-alopecia", "hypertension"],
    similarDrugSlugs: ["finasteride"],
  },
  {
    slug: "hydroxychloroquine",
    name: "Hydroxychloroquine",
    genericName: "hydroxychloroquine",
    brandNames: ["Plaquenil"],
    mechanism:
      "4-aminoquinoline that accumulates in lysosomes, modulating autophagy, antigen presentation, and cytokine signaling.",
    primaryIndication: "Rheumatoid arthritis; systemic lupus erythematosus; malaria prophylaxis",
    approvalStatus: "FDA approved",
    atcCode: "P01BA02",
    whyThisDrug:
      "Originally an antimalarial, hydroxychloroquine was repurposed for autoimmune disease based on immunomodulatory effects. COVID-19 repurposing attempts yielded insufficient evidence after large RCTs.",
    knownRisks: [
      "Retinopathy with long-term use (requires screening)",
      "QT prolongation",
      "Hypoglycemia",
      "GI upset",
    ],
    targetSlugs: ["lysosomal-pathway"],
    relatedDiseaseSlugs: ["rheumatoid-arthritis", "covid-19"],
    similarDrugSlugs: [],
  },
];

export const diseases: Disease[] = [
  {
    slug: "type-2-diabetes",
    name: "Type 2 Diabetes Mellitus",
    icd10: "E11",
    meshId: "D003924",
    description:
      "Chronic metabolic disorder characterized by insulin resistance and progressive β-cell dysfunction.",
    pathwayClusters: ["Metabolic", "Inflammatory", "Insulin signaling"],
    unmetNeed: "Cardiovascular and cancer risk reduction beyond glycemic targets.",
    relatedDrugSlugs: ["metformin"],
  },
  {
    slug: "breast-cancer",
    name: "Breast Cancer",
    icd10: "C50",
    meshId: "D001943",
    description:
      "Malignant neoplasm of breast tissue with heterogeneous molecular subtypes.",
    pathwayClusters: ["Proliferation", "Hormone signaling", "DNA repair"],
    unmetNeed: "Prevention strategies in high-risk populations; adjuvant repurposing candidates.",
    relatedDrugSlugs: ["metformin"],
  },
  {
    slug: "pulmonary-arterial-hypertension",
    name: "Pulmonary Arterial Hypertension",
    icd10: "I27.0",
    meshId: "D000081029",
    description:
      "Progressive narrowing of pulmonary arterioles leading to right heart failure.",
    pathwayClusters: ["Vascular remodeling", "Endothelial dysfunction"],
    unmetNeed: "Disease-modifying therapies beyond vasodilation.",
    relatedDrugSlugs: ["sildenafil"],
  },
  {
    slug: "multiple-myeloma",
    name: "Multiple Myeloma",
    icd10: "C90.0",
    meshId: "D009101",
    description:
      "Plasma cell malignancy characterized by bone lesions, anemia, and renal impairment.",
    pathwayClusters: ["B-cell / plasma cell", "Angiogenesis", "Bone microenvironment"],
    unmetNeed: "Relapsed/refractory disease options and combination strategies.",
    relatedDrugSlugs: ["thalidomide"],
  },
  {
    slug: "covid-19",
    name: "COVID-19",
    icd10: "U07.1",
    meshId: "D000086382",
    description:
      "Acute respiratory disease caused by SARS-CoV-2 with variable severity and systemic inflammation.",
    pathwayClusters: ["Immune hyperactivation", "Coagulation", "ACE2 axis"],
    unmetNeed: "Effective outpatient and hospitalized therapies; long COVID management.",
    relatedDrugSlugs: ["dexamethasone", "hydroxychloroquine"],
  },
  {
    slug: "tuberous-sclerosis",
    name: "Tuberous Sclerosis Complex",
    icd10: "Q85.1",
    meshId: "D014402",
    description:
      "Autosomal dominant disorder with hamartomas in multiple organs due to mTOR pathway dysregulation.",
    pathwayClusters: ["mTOR signaling", "Cell growth"],
    unmetNeed: "Non-surgical management of SEGA and renal angiomyolipoma.",
    relatedDrugSlugs: ["rapamycin"],
  },
  {
    slug: "hypothyroidism",
    name: "Hypothyroidism",
    icd10: "E03.9",
    meshId: "D007037",
    description:
      "Deficiency of thyroid hormone causing metabolic slowing, fatigue, and systemic symptoms.",
    pathwayClusters: ["Thyroid hormone signaling", "Metabolic"],
    unmetNeed: "Optimizing levothyroxine dosing and T4/T3 combination debates.",
    relatedDrugSlugs: ["levothyroxine"],
  },
  {
    slug: "cardiovascular-disease",
    name: "Cardiovascular Disease",
    icd10: "I25.9",
    meshId: "D002318",
    description:
      "Spectrum of atherosclerotic and thrombotic conditions affecting heart and vasculature.",
    pathwayClusters: ["Platelet activation", "Lipid metabolism", "Inflammation"],
    unmetNeed: "Residual risk despite statins; bleeding vs. thrombosis balance.",
    relatedDrugSlugs: ["aspirin"],
  },
  {
    slug: "benign-prostatic-hyperplasia",
    name: "Benign Prostatic Hyperplasia",
    icd10: "N40",
    meshId: "D059411",
    description:
      "Non-malignant prostate enlargement causing lower urinary tract symptoms.",
    pathwayClusters: ["Androgen signaling", "Smooth muscle proliferation"],
    unmetNeed: "Alternatives to surgery for moderate-to-severe LUTS.",
    relatedDrugSlugs: ["finasteride"],
  },
  {
    slug: "androgenetic-alopecia",
    name: "Androgenetic Alopecia",
    icd10: "L64",
    meshId: "D000505",
    description:
      "Pattern hair loss driven by androgen sensitivity and follicular miniaturization.",
    pathwayClusters: ["Androgen signaling", "Hair cycle"],
    unmetNeed: "More effective and convenient regimens with fewer side effects.",
    relatedDrugSlugs: ["finasteride", "minoxidil"],
  },
  {
    slug: "rheumatoid-arthritis",
    name: "Rheumatoid Arthritis",
    icd10: "M06.9",
    meshId: "D001172",
    description:
      "Autoimmune inflammatory arthritis with symmetric joint involvement and systemic features.",
    pathwayClusters: ["Autoimmunity", "Cytokine signaling", "Synovial inflammation"],
    unmetNeed: "Patients failing biologics; cardiovascular comorbidity management.",
    relatedDrugSlugs: ["hydroxychloroquine", "dexamethasone"],
  },
  {
    slug: "polycystic-ovary-syndrome",
    name: "Polycystic Ovary Syndrome",
    icd10: "E28.2",
    meshId: "D011085",
    description:
      "Endocrine disorder with hyperandrogenism, ovulatory dysfunction, and metabolic features.",
    pathwayClusters: ["Insulin resistance", "Androgen excess"],
    unmetNeed: "Fertility and metabolic risk management.",
    relatedDrugSlugs: ["metformin"],
  },
  {
    slug: "hypertension",
    name: "Hypertension",
    icd10: "I10",
    meshId: "D006973",
    description: "Persistently elevated arterial blood pressure.",
    pathwayClusters: ["Vascular tone", "Renin-angiotensin"],
    unmetNeed: "Resistant hypertension management.",
    relatedDrugSlugs: ["minoxidil"],
  },
  {
    slug: "erectile-dysfunction",
    name: "Erectile Dysfunction",
    icd10: "N52.9",
    meshId: "D007172",
    description: "Inability to achieve or maintain erection sufficient for intercourse.",
    pathwayClusters: ["Nitric oxide / cGMP", "Vascular"],
    unmetNeed: "Options for non-responders to PDE5 inhibitors.",
    relatedDrugSlugs: ["sildenafil"],
  },
];

export const targets: Target[] = [
  {
    slug: "ampk",
    name: "AMP-activated protein kinase",
    geneSymbol: "PRKAA1/2",
    uniprotId: "Q13131",
    description: "Energy sensor kinase regulating metabolism and cell growth.",
    pathway: "AMPK / mTOR crosstalk",
    druggability: "Indirectly modulated; direct agonists in development",
    relatedDrugSlugs: ["metformin"],
    relatedDiseaseSlugs: ["type-2-diabetes", "breast-cancer"],
  },
  {
    slug: "mTOR",
    name: "Mechanistic target of rapamycin",
    geneSymbol: "MTOR",
    uniprotId: "P42345",
    description: "Central kinase integrating nutrient and growth signals.",
    pathway: "PI3K–AKT–mTOR",
    druggability: "High (rapalogs approved)",
    relatedDrugSlugs: ["rapamycin", "metformin"],
    relatedDiseaseSlugs: ["tuberous-sclerosis", "breast-cancer"],
  },
  {
    slug: "pde5",
    name: "Phosphodiesterase-5",
    geneSymbol: "PDE5A",
    uniprotId: "O76074",
    description: "Enzyme degrading cGMP in smooth muscle.",
    pathway: "NO–cGMP signaling",
    druggability: "High (PDE5 inhibitors approved)",
    relatedDrugSlugs: ["sildenafil"],
    relatedDiseaseSlugs: ["pulmonary-arterial-hypertension", "erectile-dysfunction"],
  },
  {
    slug: "tnf-alpha",
    name: "Tumor necrosis factor alpha",
    geneSymbol: "TNF",
    uniprotId: "P01375",
    description: "Pro-inflammatory cytokine central to immune activation.",
    pathway: "TNF signaling",
    druggability: "High (biologics approved)",
    relatedDrugSlugs: ["thalidomide"],
    relatedDiseaseSlugs: ["multiple-myeloma", "rheumatoid-arthritis"],
  },
  {
    slug: "cereblon",
    name: "Cereblon",
    geneSymbol: "CRBN",
    uniprotId: "Q96SW2",
    description: "E3 ubiquitin ligase substrate receptor for IMiD immunomodulation.",
    pathway: "Protein degradation / IMiD mechanism",
    druggability: "Modulated by thalidomide analogs",
    relatedDrugSlugs: ["thalidomide"],
    relatedDiseaseSlugs: ["multiple-myeloma"],
  },
  {
    slug: "glucocorticoid-receptor",
    name: "Glucocorticoid receptor",
    geneSymbol: "NR3C1",
    uniprotId: "P04150",
    description: "Nuclear receptor mediating corticosteroid anti-inflammatory effects.",
    pathway: "HPA axis / inflammatory gene suppression",
    druggability: "High (steroids widely used)",
    relatedDrugSlugs: ["dexamethasone"],
    relatedDiseaseSlugs: ["covid-19", "rheumatoid-arthritis"],
  },
  {
    slug: "thyroid-hormone-receptor",
    name: "Thyroid hormone receptor",
    geneSymbol: "THRA/THRB",
    uniprotId: "P10827",
    description: "Nuclear receptors regulating metabolic gene transcription.",
    pathway: "Thyroid hormone signaling",
    druggability: "High (hormone replacement)",
    relatedDrugSlugs: ["levothyroxine"],
    relatedDiseaseSlugs: ["hypothyroidism"],
  },
  {
    slug: "cox1",
    name: "Cyclooxygenase-1",
    geneSymbol: "PTGS1",
    uniprotId: "P23219",
    description: "Enzyme in prostaglandin synthesis; platelet thromboxane production.",
    pathway: "Arachidonic acid / eicosanoid",
    druggability: "High (NSAIDs, aspirin)",
    relatedDrugSlugs: ["aspirin"],
    relatedDiseaseSlugs: ["cardiovascular-disease"],
  },
  {
    slug: "cox2",
    name: "Cyclooxygenase-2",
    geneSymbol: "PTGS2",
    uniprotId: "P35354",
    description: "Inducible COX isoform in inflammation.",
    pathway: "Arachidonic acid / eicosanoid",
    druggability: "High",
    relatedDrugSlugs: ["aspirin"],
    relatedDiseaseSlugs: ["cardiovascular-disease"],
  },
  {
    slug: "5-alpha-reductase",
    name: "5α-reductase",
    geneSymbol: "SRD5A2",
    uniprotId: "P31213",
    description: "Converts testosterone to dihydrotestosterone.",
    pathway: "Androgen metabolism",
    druggability: "High (finasteride approved)",
    relatedDrugSlugs: ["finasteride"],
    relatedDiseaseSlugs: ["benign-prostatic-hyperplasia", "androgenetic-alopecia"],
  },
  {
    slug: "k-atp-channel",
    name: "ATP-sensitive potassium channel",
    geneSymbol: "KCNJ11",
    uniprotId: "Q14654",
    description: "Regulates membrane potential in smooth muscle and β-cells.",
    pathway: "Vascular tone / insulin secretion",
    druggability: "Moderate",
    relatedDrugSlugs: ["minoxidil"],
    relatedDiseaseSlugs: ["hypertension", "androgenetic-alopecia"],
  },
  {
    slug: "lysosomal-pathway",
    name: "Lysosomal pathway",
    geneSymbol: "—",
    description: "Lysosomal pH and autophagy modulation.",
    pathway: "Autophagy / antigen processing",
    druggability: "Moderate (chloroquine analogs)",
    relatedDrugSlugs: ["hydroxychloroquine"],
    relatedDiseaseSlugs: ["rheumatoid-arthritis", "covid-19"],
  },
];

const pubmed = (id: string, title: string, authors: string, year: number) => ({
  id: `pmid-${id}`,
  source: "pubmed" as const,
  externalId: id,
  title,
  authors,
  year,
  url: `https://pubmed.ncbi.nlm.nih.gov/${id}/`,
});

const nct = (id: string, title: string) => ({
  id: `nct-${id}`,
  source: "clinicaltrials" as const,
  externalId: id,
  title,
  url: `https://clinicaltrials.gov/study/${id}`,
});

const fda = (id: string, title: string) => ({
  id: `fda-${id}`,
  source: "fda" as const,
  externalId: id,
  title,
  url: `https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&ApplNo=${id}`,
});

export const evidenceRecords: EvidenceRecord[] = [
  {
    slug: "metformin-breast-cancer",
    drugSlug: "metformin",
    diseaseSlug: "breast-cancer",
    targetSlug: "ampk",
    mechanism: "AMPK activation suppresses mTOR-mediated proliferation in breast epithelial cells.",
    grade: "moderate_evidence",
    evidenceTypes: ["observational", "meta_analysis", "preclinical"],
    clinicalTrialIds: ["NCT01101438"],
    pubmedIds: ["22019127", "23487376"],
    phase: "Phase II",
    outcomes:
      "Observational studies suggest reduced cancer incidence; RCTs in adjuvant setting show mixed results.",
    confidenceScore: 62,
    evidenceLevel: "Level 2b–3 (observational + preclinical)",
    aiSummary:
      "Metformin shows mechanistic plausibility and epidemiological support for breast cancer risk reduction, but prospective RCT evidence in treatment-naïve adjuvant settings remains inconclusive. Suitable for hypothesis generation and trial design, not clinical recommendation outside diabetes care.",
    aiGeneratedAt: "2026-03-15T10:00:00Z",
    lastVerified: "2026-06-28T14:30:00Z",
    lastUpdated: "2026-06-28T14:30:00Z",
    reviewStage: "published",
    citations: [
      pubmed("22019127", "Metformin and cancer risk in diabetic patients", "Decensi A et al.", 2012),
      pubmed("23487376", "Metformin and breast cancer: a systematic review", "Coleman CB et al.", 2013),
      nct("NCT01101438", "Metformin in early breast cancer (MA.32)"),
    ],
    sourcePapers: ["Decensi A et al., 2012", "Coleman CB et al., 2013"],
  },
  {
    slug: "sildenafil-pulmonary-arterial-hypertension",
    drugSlug: "sildenafil",
    diseaseSlug: "pulmonary-arterial-hypertension",
    targetSlug: "pde5",
    mechanism: "PDE5 inhibition elevates pulmonary cGMP, reducing pulmonary vascular resistance.",
    grade: "approved",
    evidenceTypes: ["clinical_trial", "fda_label"],
    clinicalTrialIds: ["NCT00033314"],
    pubmedIds: ["12925463"],
    phase: "Phase III",
    outcomes: "Improved 6-minute walk distance and hemodynamics; FDA approved as Revatio.",
    confidenceScore: 94,
    evidenceLevel: "Level 1 (RCT + regulatory approval)",
    aiSummary:
      "Sildenafil is an established, FDA-approved therapy for PAH with robust Phase III evidence. This is a validated repurposing success from erectile dysfunction research to pulmonary vascular disease.",
    aiGeneratedAt: "2026-03-15T10:00:00Z",
    lastVerified: "2026-06-25T09:00:00Z",
    lastUpdated: "2026-06-25T09:00:00Z",
    reviewStage: "published",
    citations: [
      pubmed("12925463", "Sildenafil for treatment of lung fibrosis and pulmonary hypertension", "Ghofrani HA et al.", 2003),
      nct("NCT00033314", "Sildenafil in pulmonary arterial hypertension (SUPER-1)"),
      fda("021845", "Revatio (sildenafil) FDA approval"),
    ],
    sourcePapers: ["Ghofrani HA et al., 2003"],
  },
  {
    slug: "thalidomide-multiple-myeloma",
    drugSlug: "thalidomide",
    diseaseSlug: "multiple-myeloma",
    targetSlug: "cereblon",
    mechanism: "Cereblon-dependent degradation of IKZF1/3 disrupts myeloma cell survival signaling.",
    grade: "approved",
    evidenceTypes: ["clinical_trial", "fda_label"],
    clinicalTrialIds: ["NCT00029429"],
    pubmedIds: ["11752346", "19717844"],
    phase: "Phase III",
    outcomes: "Improved response rates and survival in combination regimens; REMS mandated.",
    confidenceScore: 96,
    evidenceLevel: "Level 1 (RCT + regulatory approval)",
    aiSummary:
      "Thalidomide plus dexamethasone demonstrated significant activity in relapsed myeloma, leading to FDA approval. REMS requirements reflect teratogenicity risk. Strong approved repurposing case.",
    aiGeneratedAt: "2026-03-15T10:00:00Z",
    lastVerified: "2026-06-20T11:00:00Z",
    lastUpdated: "2026-06-20T11:00:00Z",
    reviewStage: "published",
    citations: [
      pubmed("11752346", "Thalidomide for refractory myeloma", "Singhal S et al.", 1999),
      pubmed("19717844", "Lenalidomide and dexamethasone vs dexamethasone alone", "Dimopoulos MA et al.", 2009),
      nct("NCT00029429", "Thalidomide in multiple myeloma"),
      fda("021430", "Thalomid FDA approval"),
    ],
    sourcePapers: ["Singhal S et al., 1999", "Dimopoulos MA et al., 2009"],
  },
  {
    slug: "dexamethasone-covid-19",
    drugSlug: "dexamethasone",
    diseaseSlug: "covid-19",
    targetSlug: "glucocorticoid-receptor",
    mechanism: "Glucocorticoid-mediated suppression of cytokine storm in severe COVID-19.",
    grade: "strong_repurposing_signal",
    evidenceTypes: ["clinical_trial", "meta_analysis"],
    clinicalTrialIds: ["NCT04381936"],
    pubmedIds: ["32678530"],
    phase: "Phase III (platform trial)",
    outcomes: "28-day mortality reduction in patients requiring oxygen; no benefit in mild disease.",
    confidenceScore: 91,
    evidenceLevel: "Level 1 (large RCT)",
    aiSummary:
      "The RECOVERY trial provided definitive evidence for dexamethasone 6 mg daily in hospitalized COVID-19 patients on supplemental oxygen or ventilation. WHO and NIH guidelines endorse this indication.",
    aiGeneratedAt: "2026-03-15T10:00:00Z",
    lastVerified: "2026-06-22T16:00:00Z",
    lastUpdated: "2026-06-22T16:00:00Z",
    reviewStage: "published",
    citations: [
      pubmed("32678530", "Dexamethasone in hospitalized patients with Covid-19 (RECOVERY)", "RECOVERY Collaborative Group", 2021),
      nct("NCT04381936", "RECOVERY trial"),
    ],
    sourcePapers: ["RECOVERY Collaborative Group, NEJM 2021"],
  },
  {
    slug: "rapamycin-tuberous-sclerosis",
    drugSlug: "rapamycin",
    diseaseSlug: "tuberous-sclerosis",
    targetSlug: "mTOR",
    mechanism: "mTOR inhibition reduces hamartoma growth in TSC1/TSC2-deficient cells.",
    grade: "approved",
    evidenceTypes: ["clinical_trial", "fda_label"],
    clinicalTrialIds: ["NCT00457808"],
    pubmedIds: ["19949031"],
    phase: "Phase III",
    outcomes: "Reduced SEGA volume and stabilized renal angiomyolipoma.",
    confidenceScore: 93,
    evidenceLevel: "Level 1 (RCT + regulatory approval)",
    aiSummary:
      "Everolimus and sirolimus have FDA-approved TSC indications based on Phase III trials demonstrating tumor volume reduction. Mechanistically grounded in TSC–mTOR pathway biology.",
    aiGeneratedAt: "2026-03-15T10:00:00Z",
    lastVerified: "2026-06-18T10:00:00Z",
    lastUpdated: "2026-06-18T10:00:00Z",
    reviewStage: "published",
    citations: [
      pubmed("19949031", "Sirolimus for angiomyolipoma in tuberous sclerosis", "Bissler JJ et al.", 2010),
      nct("NCT00457808", "Everolimus for SEGA in TSC"),
      fda("021560", "Rapamune (sirolimus)"),
    ],
    sourcePapers: ["Bissler JJ et al., 2010"],
  },
  {
    slug: "levothyroxine-hypothyroidism",
    drugSlug: "levothyroxine",
    diseaseSlug: "hypothyroidism",
    targetSlug: "thyroid-hormone-receptor",
    mechanism: "Exogenous T4 restores normal thyroid hormone levels and metabolic homeostasis.",
    grade: "approved",
    evidenceTypes: ["clinical_trial", "fda_label", "meta_analysis"],
    clinicalTrialIds: [],
    pubmedIds: ["23846913"],
    outcomes: "Normalization of TSH and symptom improvement; decades of clinical use.",
    confidenceScore: 98,
    evidenceLevel: "Level 1 (guideline-endorsed standard of care)",
    aiSummary:
      "Levothyroxine is the established first-line therapy for hypothyroidism with FDA-approved labeling, ATA/AACE guideline endorsement, and extensive long-term safety data. This is primary-use evidence rather than repurposing, but represents gold-standard drug–disease pairing.",
    aiGeneratedAt: "2026-03-15T10:00:00Z",
    lastVerified: "2026-07-01T08:00:00Z",
    lastUpdated: "2026-07-01T08:00:00Z",
    reviewStage: "published",
    citations: [
      pubmed("23846913", "ATA guidelines for hypothyroidism", "Jonklaas J et al.", 2014),
      fda("021402", "Synthroid (levothyroxine) FDA label"),
    ],
    sourcePapers: ["Jonklaas J et al., Thyroid 2014"],
  },
  {
    slug: "aspirin-cardiovascular-disease",
    drugSlug: "aspirin",
    diseaseSlug: "cardiovascular-disease",
    targetSlug: "cox1",
    mechanism: "Irreversible COX-1 inhibition reduces thromboxane A2-mediated platelet aggregation.",
    grade: "approved",
    evidenceTypes: ["clinical_trial", "meta_analysis", "fda_label"],
    clinicalTrialIds: ["NCT00139815"],
    pubmedIds: ["12102808"],
    phase: "Multiple Phase III trials",
    outcomes: "Reduced major vascular events in secondary prevention; primary prevention benefit-risk varies by age.",
    confidenceScore: 92,
    evidenceLevel: "Level 1 (meta-analysis of RCTs)",
    aiSummary:
      "Low-dose aspirin has Level 1 evidence for secondary cardiovascular prevention. Primary prevention guidelines have narrowed due to bleeding risk in lower-risk populations (ASPREE, ARRIVE trials).",
    aiGeneratedAt: "2026-03-15T10:00:00Z",
    lastVerified: "2026-06-26T12:00:00Z",
    lastUpdated: "2026-06-26T12:00:00Z",
    reviewStage: "published",
    citations: [
      pubmed("12102808", "Antithrombotic Trialists' Collaboration meta-analysis", "Antithrombotic Trialists' Collaboration", 2002),
      nct("NCT00139815", "ASPREE trial"),
    ],
    sourcePapers: ["Antithrombotic Trialists' Collaboration, Lancet 2002"],
  },
  {
    slug: "finasteride-benign-prostatic-hyperplasia",
    drugSlug: "finasteride",
    diseaseSlug: "benign-prostatic-hyperplasia",
    targetSlug: "5-alpha-reductase",
    mechanism: "DHT reduction decreases prostate volume and improves urinary flow.",
    grade: "approved",
    evidenceTypes: ["clinical_trial", "fda_label"],
    clinicalTrialIds: ["NCT00021880"],
    pubmedIds: ["7688365"],
    phase: "Phase III",
    outcomes: "Reduced prostate volume, improved symptom scores vs placebo.",
    confidenceScore: 95,
    evidenceLevel: "Level 1 (RCT + regulatory approval)",
    aiSummary:
      "Finasteride is FDA-approved for BPH with Phase III PLESS trial evidence demonstrating symptom and volume benefits. 5α-reductase mechanism directly addresses disease pathophysiology.",
    aiGeneratedAt: "2026-03-15T10:00:00Z",
    lastVerified: "2026-06-24T09:30:00Z",
    lastUpdated: "2026-06-24T09:30:00Z",
    reviewStage: "published",
    citations: [
      pubmed("7688365", "Finasteride in benign prostatic hyperplasia (PLESS)", "McConnell JD et al.", 1993),
      nct("NCT00021880", "PLESS trial"),
      fda("020180", "Proscar (finasteride)"),
    ],
    sourcePapers: ["McConnell JD et al., NEJM 1993"],
  },
  {
    slug: "minoxidil-androgenetic-alopecia",
    drugSlug: "minoxidil",
    diseaseSlug: "androgenetic-alopecia",
    targetSlug: "k-atp-channel",
    mechanism: "Topical minoxidil prolongs anagen phase; VEGF upregulation may promote follicular perfusion.",
    grade: "approved",
    evidenceTypes: ["clinical_trial", "fda_label"],
    clinicalTrialIds: ["NCT00191501"],
    pubmedIds: ["9777765"],
    phase: "Phase III",
    outcomes: "Increased hair count and patient-reported improvement vs vehicle.",
    confidenceScore: 88,
    evidenceLevel: "Level 1 (RCT + regulatory approval)",
    aiSummary:
      "Topical minoxidil is FDA-approved for androgenetic alopecia, repurposed from oral antihypertensive hypertrichosis observations. Efficacy is modest but well-established in RCTs.",
    aiGeneratedAt: "2026-03-15T10:00:00Z",
    lastVerified: "2026-06-27T15:00:00Z",
    lastUpdated: "2026-06-27T15:00:00Z",
    reviewStage: "published",
    citations: [
      pubmed("9777765", "Topical minoxidil for androgenetic alopecia", "Olsen EA et al.", 2002),
      nct("NCT00191501", "Minoxidil topical solution trial"),
      fda("020834", "Rogaine (minoxidil)"),
    ],
    sourcePapers: ["Olsen EA et al., 2002"],
  },
  {
    slug: "hydroxychloroquine-covid-19",
    drugSlug: "hydroxychloroquine",
    diseaseSlug: "covid-19",
    targetSlug: "lysosomal-pathway",
    mechanism: "Proposed antiviral and immunomodulatory effects via lysosomal pH and autophagy.",
    grade: "insufficient_evidence",
    evidenceTypes: ["clinical_trial", "meta_analysis"],
    clinicalTrialIds: ["NCT04381936", "NCT04332991"],
    pubmedIds: ["33031652"],
    phase: "Multiple Phase III (negative)",
    outcomes: "Large RCTs (RECOVERY, SOLIDARITY) showed no mortality benefit; not recommended.",
    confidenceScore: 12,
    evidenceLevel: "Level 1 (negative RCTs)",
    aiSummary:
      "Despite early enthusiasm, hydroxychloroquine lacks efficacy for COVID-19. RECOVERY and SOLIDARITY trials demonstrated no benefit; WHO recommends against use. Important negative repurposing example.",
    aiGeneratedAt: "2026-03-15T10:00:00Z",
    lastVerified: "2026-06-29T10:00:00Z",
    lastUpdated: "2026-06-29T10:00:00Z",
    reviewStage: "published",
    citations: [
      pubmed("33031652", "Repurposed antiviral drugs for COVID-19 (SOLIDARITY)", "WHO Solidarity Consortium", 2021),
      nct("NCT04332991", "SOLIDARITY trial"),
    ],
    sourcePapers: ["WHO Solidarity Consortium, NEJM 2021"],
  },
];

export const reviewQueue: ReviewQueueItem[] = [
  {
    evidenceSlug: "metformin-polycystic-ovary-syndrome",
    stage: "ai_draft",
    notes: "AI draft generated; awaiting scientific reviewer assignment.",
    updatedAt: "2026-07-05T09:00:00Z",
  },
  {
    evidenceSlug: "finasteride-androgenetic-alopecia",
    stage: "scientific_review",
    assignedTo: "scientific-reviewer@example.com",
    notes: "Citation audit in progress.",
    updatedAt: "2026-07-04T14:00:00Z",
  },
];

export const auditLogs: AuditLogEntry[] = [
  {
    id: "audit-001",
    timestamp: "2026-07-01T08:00:00Z",
    action: "evidence.verified",
    actor: "medical-reviewer@example.com",
    resource: "levothyroxine-hypothyroidism",
    details: "Annual verification completed; FDA label current.",
  },
  {
    id: "audit-002",
    timestamp: "2026-06-29T10:00:00Z",
    action: "evidence.published",
    actor: "medical-reviewer@example.com",
    resource: "hydroxychloroquine-covid-19",
    details: "Published with insufficient_evidence grade after SOLIDARITY review.",
  },
  {
    id: "audit-003",
    timestamp: "2026-06-28T14:30:00Z",
    action: "evidence.verified",
    actor: "scientific-reviewer@example.com",
    resource: "metformin-breast-cancer",
    details: "PubMed citations re-validated.",
  },
];
